import { getDB } from "./lib/mongodb.js";
import {
  comparePassword,
    createToken
    } from "./lib/auth.js";

    export default async (request) => {

      if (request.method !== "POST") {
          return Response.json(
                {
                        success: false,
                                message: "Method not allowed"
                                      },
                                            {
                                                    status: 405
                                                          }
                                                              );
                                                                }

                                                                  try {

                                                                      const {
                                                                            identifier,
                                                                                  password
                                                                                      } = await request.json();

                                                                                          if (!identifier || !password) {
                                                                                                return Response.json(
                                                                                                        {
                                                                                                                  success: false,
                                                                                                                            message:
                                                                                                                                        "Identifier and password are required"
                                                                                                                                                },
                                                                                                                                                        {
                                                                                                                                                                  status: 400
                                                                                                                                                                          }
                                                                                                                                                                                );
                                                                                                                                                                                    }

                                                                                                                                                                                        const db = await getDB();

                                                                                                                                                                                            const user =
                                                                                                                                                                                                  await db.collection("users").findOne({
                                                                                                                                                                                                          $or: [
                                                                                                                                                                                                                    { registerNumber: identifier },
                                                                                                                                                                                                                              { idNumber: identifier },
                                                                                                                                                                                                                                        { phone: identifier }
                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                          // Temporary debugging logs
                                                                                                                                                                                                                                                              console.log(
                                                                                                                                                                                                                                                                    "Login identifier:",
                                                                                                                                                                                                                                                                          identifier
                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                  console.log(
                                                                                                                                                                                                                                                                                        "User found:",
                                                                                                                                                                                                                                                                                              user
                                                                                                                                                                                                                                                                                                      ? user.registerNumber
                                                                                                                                                                                                                                                                                                              : "NO USER"
                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                      if (!user) {
                                                                                                                                                                                                                                                                                                                            return Response.json(
                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                              success: false,
                                                                                                                                                                                                                                                                                                                                                        message:
                                                                                                                                                                                                                                                                                                                                                                    "Invalid login credentials"
                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                              status: 401
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                    const passwordCorrect =
                                                                                                                                                                                                                                                                                                                                                                                                                          await comparePassword(
                                                                                                                                                                                                                                                                                                                                                                                                                                  password,
                                                                                                                                                                                                                                                                                                                                                                                                                                          user.password
                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Password correct:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                passwordCorrect
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!passwordCorrect) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return Response.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          message:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Invalid login credentials"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status: 401
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const token =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            createToken(user);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Response.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      message: "Login successful",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              token,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      user: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id: user._id.toString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name: user.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    registerNumber:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                user.registerNumber,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          idNumber:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      user.idNumber,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                phone: user.phone,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          role: user.role,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    department:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                user.department
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            status: 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Login error:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Response.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      message:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                error.message ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Login failed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              status: 500
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };